### <center>Lists & Numpy Arrays</center>

In [1]:
import numpy as np

# tuples are immutable
tuple = (1,2,3)
# cannot perform: tuple(0) = 0

In [2]:
list_1 = list(range(0,10))
print(list_1)
print(type(list_1))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [3]:
list_2 = [3*x for x in range(0,int(30/3))]
print(list_2)
print(type(list_2))

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]
<class 'list'>


In [4]:
# Python lists are not the same as a NumPy array
# Operations on NumPy arrays are more efficient

In [5]:
np_array_1 = np.linspace(0, 10, 11)
print(np_array_1)
print(type(np_array_1))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [6]:
np_array_2 = np.arange(0,10)
print(np_array_2)
print(type(np_array_2))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [7]:
np_array_3 = np.array( [ [2,3,5], [7,11,13]] )
print(np_array_3)

[[ 2  3  5]
 [ 7 11 13]]


In [8]:
ones = np.ones((3,3))
print(ones)

zeros = np.zeros((3,3))
print('\n', zeros)

np_zeros = np.array([[0]*3, [0]*3, [0]*3], dtype=float)
print('\n', np_zeros)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
multi_dim = np.array([[1,0,0], [0,1,0], [0,0,1]])
print(multi_dim)

multi_dim1 = np.eye(3)
print(multi_dim1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
a = np.zeros( (2, 3) )
b = np.ones( (2, 3) )

stack_1 = np.hstack( [a, b] )
print(stack_1)
print(stack_1[1][2])

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
0.0


In [11]:
a = np.arange(20)
print(a)
print(a[:])
print(a[::])
print(a[5:15])
print(a[5:15:3])
print(a[5::])
print(a[:5:])
print(a[::5])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5  6  7  8  9 10 11 12 13 14]
[ 5  8 11 14]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4]
[ 0  5 10 15]


In [12]:
a = np.array( [ [1, 2], [2, 1] ] )
print(a)
b = a.flatten()
print(b)
c = np.ravel(a)
print(c)

b[1] = 11 # Doesn't change the data in a
c[2] = 22 # Does change the data in a
print(b)
print(c)
print(a)

[[1 2]
 [2 1]]
[1 2 2 1]
[1 2 2 1]
[ 1 11  2  1]
[ 1  2 22  1]
[[ 1  2]
 [22  1]]
